implement aligned new and delete operators
- compiler option `-faligned-allocation` is required, otherwise use of
  such operators results in error, e.g.:

    error: aligned deallocation function of type 'void (void *, enum std::align_val_t) noexcept' is not available on z/OS
       28 |   auto ptr = new(std::align_val_t{al}) int;
          |               ^
    note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic

- pass `-m64` to linker flags