enable zoslib to build with clang (#64)
- Rewrite STORAGE OBTAIN in anon_inner_mmap() and STORAGE RELEASE in
  anon_munmap_inner(), otherwise STORAGE and SYSDATE statements fail
  with error: unexpected token in argument list.
- Rewrite asm in __testread(), otherwise it fails with error:
  The HLASM Label has to be an Identifier
  __asm volatile("&suffix SETA &suffix+1\n" due to '&suffix'.
- Replace b'....' and x'........' by their decimal equivalent, otherwise
  error: unexpected token in argument list.
- Use volatile in asm statements.
  At -O2 and above, certain inline asm blocks within functions are
  eliminated because LLVM thinks its dead code. This is also consistent
  with Tobey in njsc and xlclang, which internally adds volatile to asm
  blocks.
- Move getentropy() and its helpers to its own source, as its PRNO
  instruction requires arch z14.
- Init variables before use and remove unused variables.
- Include features.h before checking __TARGET_LIB__.
- Change constraint to 'a' to avoid using r0 in __iarv64() asm.
  The PC instruction SIGILLs when compiled at -O0, because at -O0
  Wyvern generates pc 0(0), and it seems r0 is not valid for PC.
  At higher optimization levels Wyvern uses a different register,
  e.g. pc 0(6) is generated, which works. The constraint "a" which
  stands for "address register", uses all registers except r0.
- Remove registers from clobbers list if they're in input or output.
- Add missing registers in __testread()'s clobbers list.
- Exclude CSRSIC header.
  This is temporary until Woz supports OS linkage, otherwise
  `extern "OS" ??` fails to compile.
- Fix 2048 offset in stack_addr to bytes instead of words.

Co-authored-by: Anirudh Prasad
Co-authored-by: Igor Todorovski <itodorov@ca.ibm.com>
Co-authored-by: Kai Nacke <kai.peter.nacke@ibm.com>