src: replace use of alloca()
Since it's not part of any standard (fails to compile
with -std=c++20 with error: use of undeclared identifier 'alloca').